backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"

    label: "Pages"
    files:
      - file: "src/pages/success.md"
        label: "Success"
        name: "success"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "success-page",
            }
          - { label: Content, name: content, widget: "markdown" }
          - {
              label: "Icon",
              name: icon,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
      - file: "src/pages/index.md"
        label: "Index"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: "markdown" }
          - {
              label: "Top Icons",
              name: topIcons,
              widget: object,
              fields:
                [
                  {
                    label: "Icon 1",
                    name: icon1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Label, name: label, widget: string },
                      ],
                  },
                  {
                    label: "Icon 2",
                    name: icon2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Label, name: label, widget: string },
                      ],
                  },
                  {
                    label: "Icon 3",
                    name: icon3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Label, name: label, widget: string },
                      ],
                  },
                  {
                    label: "Icon 4",
                    name: icon4,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Label, name: label, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: "Packages",
              name: packages,
              widget: object,
              fields:
                [
                  {
                    label: "Package 1",
                    name: package1,
                    widget: object,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: "Learn More Link",
                          name: link,
                          widget: string,
                        },
                        {
                          label: Bullets,
                          name: bullets,
                          widget: list,
                          field: { label: Text, name: text, widget: string },
                        },
                      ],
                  },
                  {
                    label: "Package 2",
                    name: package2,
                    widget: object,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: "Learn More Link",
                          name: link,
                          widget: string,
                        },
                        {
                          label: Bullets,
                          name: bullets,
                          widget: list,
                          field: { label: Text, name: text, widget: string },
                        },
                      ],
                  },
                  {
                    label: "Package 3",
                    name: package3,
                    widget: object,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: "Learn More Link",
                          name: link,
                          widget: string,
                        },
                        {
                          label: Bullets,
                          name: bullets,
                          widget: list,
                          field: { label: Text, name: text, widget: string },
                        },
                      ],
                  },
                ],
            }
          - {
              label: "Testimonials",
              name: testimonials,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: "Testimonial 1",
                    name: testimonial1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Name, name: name, widget: string },
                        { label: Text, name: text, widget: string },
                      ],
                  },
                  {
                    label: "Testimonial 2",
                    name: testimonial2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Name, name: name, widget: string },
                        { label: Text, name: text, widget: string },
                      ],
                  },
                  {
                    label: "Testimonial 3",
                    name: testimonial3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Name, name: name, widget: string },
                        { label: Text, name: text, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Partners,
              name: partners,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Items,
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }

  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      # - file: "src/pages/navbar/index.md"
      #   label: "Navbar"
      #   name: "navbar"
      #   fields:
      #     - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
      #     - {
      #         label: "Menu Items",
      #         name: "menuItems",
      #         widget: "list",
      #         fields:
      #           [
      #             { label: "Label", name: "label", widget: "string" },
      #             { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
      #             { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
      #           ],
      #       }
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "Links",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }